sharindata:
  image: registry.gitlab.com/anthonykgross/sharindata:master
  volumes:
    - ./conf/php5:/etc/php5
    - ./conf/supervisor:/etc/supervisor/conf.d
    - ./conf/nginx:/etc/nginx
    - ./src:/src
    - ./logs:/logs
  environment:
    VIRTUAL_HOST: "sharindata.anthonykgross.fr,sharindata.anthonykgross.local"