sharindata:
  image: akg-sharindata:latest
  volumes:
    - ./conf/php5:/etc/php5
    - ./conf/supervisor:/etc/supervisor/conf.d
    - ./conf/nginx:/etc/nginx
    - ./src:/src
    - ./logs:/logs
  ports:
    - 80:80
  environment:
    VIRTUAL_HOST: "sharindata.com,sharindata.local"