kkuet_net_sharindata:
    resource: "@KkuetNetSharindataBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#liste_rest:
#    resource: Activpik\WebserviceBundle\Controller\ListeController
#    prefix: /api
#    type: rest
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/docs