kkuet_net_sharindata:
    resource: "@KkuetNetSharindataBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: KkuetNetSharindataBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

security_rest:
    resource: KkuetNet\SharindataBundle\Controller\SecurityController
    prefix: /api/token
    type: rest
    
currency_rest:
    resource: KkuetNet\SharindataBundle\Controller\CurrencyController
    prefix: /api/data
    type: rest
    
country_rest:
    resource: KkuetNet\SharindataBundle\Controller\CountryController
    prefix: /api/data
    type: rest

language_rest:
    resource: KkuetNet\SharindataBundle\Controller\LanguageController
    prefix: /api/data
    type: rest
 
timezone_rest:
    resource: KkuetNet\SharindataBundle\Controller\TimezoneController
    prefix: /api/data
    type: rest

zone_rest:
    resource: KkuetNet\SharindataBundle\Controller\ZoneController
    prefix: /api/data
    type: rest

image_rest:
    resource: KkuetNet\SharindataBundle\Controller\ImageController
    prefix: /api/tool
    type: rest
    
randomize_rest:
    resource: KkuetNet\SharindataBundle\Controller\RandomizeController
    prefix: /api/tool
    type: rest

converter_rest:
    resource: KkuetNet\SharindataBundle\Controller\ConverterController
    prefix: /api/tool
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/docs
    
fos_user_registration_register:
    pattern: /register
    defaults: { _controller: KkuetNetSharindataBundle:User:register }