jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        wsse_secured:
#           Pas de restrinctions si on souhaite aller aur la doc ou creer/supprimer le token
#            pattern:   ^/api/(?!(docs|token)).*
            pattern:   ^/api/(?!(.*))
            wsse:      { nonce_dir: "%kernel.cache_dir%/nonces/", lifetime: 300, realm: "Secured API", profile: "UsernameToken"}
        main:
#           La session principal n'est pas valable dans la partie API
            pattern: ^/(?!(api)).*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
        

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }